<?php

namespace App\Filament\Resources\PDFSnapshots\Schemas;

use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class PDFSnapshotForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->columns(1)
            ->components([
                Section::make('Important Note')
                    ->description('PDF Snapshots are automatically created when a Job Application send status changes to "Sent". Manual creation is not recommended.')
                    ->icon('heroicon-o-information-circle')
                    ->schema([
                        Placeholder::make('info')
                            ->label('')
                            ->content('⚠️ PDF Snapshots are typically auto-generated by the system when you mark a job application as sent. The PDF file and hash are automatically created from the linked CV. Manual creation is only for advanced use cases.'),
                    ]),

                Section::make('Snapshot Information')
                    ->description('Link this snapshot to a job application')
                    ->icon('heroicon-o-camera')
                    ->columns(2)
                    ->schema([
                        Select::make('job_application_id')
                            ->label('Job Application')
                            ->relationship('jobApplication', 'company_name')
                            ->required()
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->helperText('The job application this PDF was sent for'),

                        Select::make('cv_id')
                            ->label('CV')
                            ->relationship('cv', 'title')
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->helperText('The base CV used'),

                        Select::make('cv_version_id')
                            ->label('CV Version')
                            ->relationship('cvVersion', 'reason')
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->helperText('Optional: Specific CV version snapshot')
                            ->columnSpan(2),
                    ]),

                Section::make('File Details (Auto-Generated)')
                    ->description('These fields are automatically populated when created through the system')
                    ->icon('heroicon-o-document')
                    ->schema([
                        TextInput::make('file_path')
                            ->label('PDF File Path')
                            ->required()
                            ->maxLength(500)
                            ->placeholder('pdf-snapshots/123_abc123.pdf')
                            ->helperText('Auto-generated: Storage path for the PDF file')
                            ->disabled()
                            ->dehydrated(),

                        TextInput::make('hash')
                            ->label('File Hash (SHA-256)')
                            ->required()
                            ->maxLength(64)
                            ->placeholder('abc123...')
                            ->helperText('Auto-generated: SHA-256 hash for file integrity verification')
                            ->disabled()
                            ->dehydrated(),
                    ]),
            ]);
    }
}
