<?php

namespace App\Filament\Resources\PDFSnapshots\Pages;

use App\Filament\Resources\PDFSnapshots\PDFSnapshotResource;
use Filament\Resources\Pages\ListRecords;

class ListPDFSnapshots extends ListRecords
{
    protected static string $resource = PDFSnapshotResource::class;

    protected ?string $heading = 'PDF Snapshots';

    protected function getHeaderActions(): array
    {
        return [
            // No actions - PDF Snapshots are auto-generated by the system
        ];
    }
}
